### ISSUE TITLE
R CMD check failure with rstan 2.13.2

### ISSUE THREAD

**Issue by bgoodri** [cdriveraus/ctsem#1]
This line

https://github.com/cdriveraus/ctsem/blob/master/R/ctStanFit.R#L1049

causes `R CMD check --as-cran` to fail because it forks as many times as there are cores on the machine. It should say `cores = min(chains, parallel::detectCores())`.

More generally, we have a bunch of recommendations for R packages that use Stan at
https://cran.r-project.org/web/packages/rstantools/vignettes/developer-guidelines.html
In particular, it would be much better if you converted the `writemodel` function into a .stan file or .stan files with branching logic that were compiled when the package is built on CRAN.

**Comment by cdriveraus** [comment]
Thanks, fixed, will post to cran shortly. do you know if something changed in Stan that caused this to become apparent? I don't know why it slipped through before. Re the general comments - yes there is plenty that can be tidied up or improved still, they are nice guidelines in general, but it's not obvious to me how to convert to using .stan files without a lot of work and maintenance headaches - if you say that is not the case then I'll push it further up my to-do list.

**Comment by bgoodri** [comment]
What changed in rstan is that it now uses `mclapply` in a non-Windows, non-GUI setting and in that case, I forgot to check that cores <= chains like I did before when it was always using socket clusters.

Converting to an rstanarm-style package with precompiled models is probably an hour of work (and it took a month of work to get `rstan.package.skeleton` right) but I know from experience that it is easier to maintain and test. Basically, your  `writemodel` function has stuff like

```
',if(n.TIpred > 0) paste0('int<lower=0> ntipred; // number of time independent covariates
matrix[nsubjects,ntipred] tipreds; '),'
```
and you should just declare `ntipred` and `tipreds` unconditionally in the `data` block of a .stan file. If `ntipred` is zero then `tipreds` will be a `nsubjects` by zero matrix, which is fine in Stan, although you do need to pass in such a matrix. If necessary, you can put an `if (ntipred > 0) {}` clause into subsequent Stan blocks. The same sort of thing should hold for most or all the conditional logic in `writemodel`.

Also, a lot of the stuff in your `functions` block is unnecessary now. Stan 2.13.x has matrix exponential, vectorized sqrt functions, etc.

**Comment by cdriveraus** [comment]
Ok thanks. I think most of the logic translates just fine, the mechanism for creating matrices of fixed and free parameters will need more thought though...

**Comment by bgoodri** [comment]
If you have more questions, let us know. Besides rstanarm, there are more
examples of doing it this way in the beanz, bmlm, dfpk, and eggCounts
packages.
