### ISSUE TITLE
plot.ctStanFit error when plotting posterior densities

### ISSUE THREAD

**Issue by ryanoisin** [cdriveraus/ctsem#20]
Hi Charlie. I noticed when I try to plot a `ctStanFit` object i get an error when attempting to plot the posterior densities:
`Plotting posterior density estimates using stan_dens; Error in .mode_check(object) : is.stanfit(object) is not TRUE`

Running `rstan::stan_dens(object$stanfit)` returns the same error message. However, running `rstan::stan_dens(object$stanfit$stanfit)` is successful. Perhaps a typo on lines 97 and 100 of `plot.ctStanFit.R` , because i see the second level `stanfit` object is called for the trace plots. 

I'm running ctsem 3.5.3, rstan 2.21.2 and StanHeaders 2.21.0-7 on:
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

**Comment by cdriveraus** [comment]
Is this when you manually request a plot with type ='density' on a fit where optimization (the default) was used? This is not really a bug but it could have a more informative error. stan based plots are only available if you use stan's HMC sampler, which will be much slower in general but gives more precise posterior estimates. If I'm wrong and this is occurring in some other situation, tell me the specifics :)

**Comment by ryanoisin** [comment]
No, it's happening when I'm running the following
`ctfit <- ctStanFit(data, ctmodel, optimize = FALSE, chains = 3)` (or `chains = 2`)
`plot(ctfit)`

The above works for the first two sets of plots (temporal regressions and trace plots) but throws an error on the third set (densities). What does work, however is using
`rstan::stan_dens(ctfit$stanfit$stanfit)`

So, estimating the model as intended, but obtaining

> rstan:::is.stanfit(ctfit)
[1] FALSE
> rstan:::is.stanfit(ctfit$stanfit)
[1] FALSE
> rstan:::is.stanfit(ctfit$stanfit$stanfit)
[1] TRUE 


I'm not sure what the nesting logic is here (why the second level `stanfit` object is the one to use, not the first level). But i can see that in `plot.ctStanFit.R` you pretty consistently use the second level object, apart from when it comes to the density plots - see lines 97 and 100 respectively

**Comment by cdriveraus** [comment]
I see, thanks for checking / reporting then, fix is pushed. The nesting logic is really dumb and due to unexpected downstream consequences of on the fly development :) the second $stanfit layer only exists when HMC is used.
