### ISSUE TITLE
ctStanSubjectPars(..., pointest = FALSE)

### ISSUE THREAD

**Issue by ryanoisin** [cdriveraus/ctsem#27]
Hi Charlie,

Noticed an issue when using ctStanSubjectPars(..., pointest = FALSE) to extract posterior draws of subject-specific parameters. I've fit the model in a seperate session, and receive the error 
`Error in stan_unconstrainsamples(object$stanfit$stanfit) : 
  stanfit object must be reinitialized but no data is provided`

I've tracked the issue down.  `ctStanSubjectPars()` calls `ctExtract()` (line 36 `summary.ctStanFit.R`)
`tfp <- ctExtract(fit,subjectMatrices = TRUE,cores=cores,nsamples=nsamples)`

`ctExtract()` then calls `stan_unconstrainsamples()`  (line 32 `extract.ctStanFit.R`) 
` samps <- t(stan_unconstrainsamples(object$stanfit$stanfit))`
The problem is that stan_unconstrainsamples() should also specify a `standata` argument. I could get the function call to work properly by changing the above line to
`  samps <- t(stan_unconstrainsamples(object$stanfit$stanfit,  standata = object$standata))`

I think that should resolve the issue, but I'm not totally clear on what the different uses are for `stan_constrainsamples` and `stan_unconstrainsamples`

**Comment by cdriveraus** [comment]
Thanks a lot Oisin, and nice work tracking that one through the function maze!
