### ISSUE TITLE
Problem with ctKalman function

### ISSUE THREAD

**Issue by blainmorin** [cdriveraus/ctsem#30]
Hi Charles,

After updating, I think there is an issue with ctKalmain(). 

I think the error is here:

`subjects <- idmap[which(idmap[, 1] %in% subjects), 2]`

because it returns an empty vector. 

Not 100% sure that is the cause, but am unable to run some code from the previous version. 

Thank you!

**Comment by cdriveraus** [comment]
Thanks for the report -- do I understand correctly that things work fine so long as everything was fit with the latest version, but the latest version of ctKalman does not play nicely with fit objects from earlier ctsem versions? If that's the case then I don't think I can fix this, but in at least some cases like this the ctFitUpdate function is helpful for bringing an older fit object in line with newer version internals.

**Comment by cdriveraus** [comment]
I see, thanks a lot. It's not 'strictly' an error but rather just poor coding practice re backwards compatibility -- in the 2nd example, you really need to specify `subjects=c('2a',3a','4a')`, but that doesn't match up with earlier versions so I've pushed a fix that allows both specifications (and warns if integers are used when `realid=TRUE`, which is the default)
