### ISSUE TITLE
browser() in sgd

### ISSUE THREAD

**Issue by ryanoisin** [cdriveraus/ctsem#36]
In `sgd.R`  line 130 you have a browser call `if(any(is.na(newpars))) browser()`. I can imagine this is helpful when debugging, or possibly when running a single model at a time to investigate what parameter is being sampled incorrectly. But this is problematic when running simulations because it stops the simulation run entirely when the browser call is activated. It is probably better to replace this with a `stop()` call and informative error message. Alternatively you could make `debugging` with browser an option which you can feed to ctStanFit (and then stanoptimis), e.g. `if(any(is.na(newpars))){ if(isTRUE(debugging) browser() else stop()}`

**Comment by cdriveraus** [comment]
yes you're right I made a couple of small failed attempts to fix this properly already, I will just fail it and try an alternative optimization approach though -- on my list :)

**Comment by ryanoisin** [comment]
Great! any chance you could replace the browser call with stop in the meantime on the github version? Then I can finish my last simulation condition without cloning the current version :D

**Comment by cdriveraus** [comment]
oh and you can avoid the stochastic optimizer by setting optimcontrol=list(stochastic=FALSE, nsubsets=1) as an argument when fitting. the old default of bfgs is often faster on simple models but slower and less robust once the models get complicated.
