### ISSUE TITLE
unable to update ctsem

### ISSUE THREAD

**Issue by beew** [cdriveraus/ctsem#4]
R 3.4.4
OS Ubuntu 16.04.4 64 bits
I tried to update ctsem from 2.5.0 to 2.6.4 and got these errors

```
* installing *source* package ‘ctsem’ ...
** package ‘ctsem’ successfully unpacked and MD5 sums checked
** libs
"/usr/lib/R/bin/Rscript" -e "source(file.path('..', 'tools', 'make_cc.R')); make_cc(commandArgs(TRUE))" stan_files/ctsm.stan
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '../tools/make_cc.R': No such file or directory
Execution halted
Makevars:17: recipe for target 'stan_files/ctsm.cc' failed
make: *** [stan_files/ctsm.cc] Error 1
ERROR: compilation failed for package ‘ctsem’
* removing ‘/usr/lib/R/library/ctsem’
* restoring previous ‘/usr/lib/R/library/ctsem’

The downloaded source packages are in
	‘/tmp/RtmpmAN7Mp/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘ctsem’ had non-zero exit status
```
Please advise
Thanks.

**Comment by beew** [comment]
I figured it out.

The problem is that ctsem's install script assumes R's working directory is the user's $HOME on Linux. But mine is in $HOME/R  since I don't want to dump R files all over my $HOME. I have setwd("~/R") in my .RProfile. Commenting out this line in .RProfile and restarting R the installation went through. After successfully installing ctsem I uncommented the setwd line in .RProfile and restarted R, ctsem loaded with no problem.

I think this should be a bug since the install script should be able to find the user's working directory. I have no such issue except rstanarm (no problem with rstan itself)

**Comment by cdriveraus** [comment]
Thanks very  much for the detailed report, I agree this shouldn't occur. ctsem was integrated with rstan using rstantools, which seems to rely on files from rstanarm, hence the same issue with ctsem and rstanarm. I'll get a fix out shortly.

**Comment by cdriveraus** [comment]
ah, seeing Ben's comment re rstanarm, https://github.com/stan-dev/rstanarm/issues/293, I guess I will leave this be for the moment at least...

**Comment by ssalimi** [comment]
package ‘ctsem’ is not available (for R version 4.0.0)
Is there any way around this or I just should go to the older R version?
Thanjs

**Comment by cdriveraus** [comment]
It's available just taking forever to get back on CRAN after various dramas. The github version can be installed via:
source(file = 'https://github.com/cdriveraus/ctsem/raw/master/installctsem.R')

**Comment by ssalimi** [comment]
Yes, it was installed using the source. 
Thanks.
