### ISSUE TITLE
Broken Vignette Manual's Citations?

### ISSUE THREAD

**Issue by emstruong** [cdriveraus/ctsem#46]
Hello,

The in-text citations of the manual on [CRAN](https://cran.r-project.org/package=ctsem/vignettes/hierarchicalmanual.pdf) seem to be broken or at the very least, they're certainly going out of bounds.

**Comment by cdriveraus** [comment]
Thanks! Definitely broken. You can use https://raw.githubusercontent.com/cdriveraus/ctsem/master/vignettes/hierarchicalmanual.pdf until I figure out a fix.

**Comment by emstruong** [comment]
> Thanks! Definitely broken. You can use https://raw.githubusercontent.com/cdriveraus/ctsem/master/vignettes/hierarchicalmanual.pdf until I figure out a fix.

Thanks!
